apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    tracing:
      enabled: true
  profile: default
  values:
    meshConfig:
      enableAutoMtls: true
    gateways:
      istio-ingressgateway:
        type: NodePort
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
