apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
