---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
    version: v1
  name: api-gateway
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      version: v1
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/path: "/actuator/prometheus"
        kiali.io/dashboards: micrometer-1.1-jvm,micrometer-1.0.6-jvm-pool,envoy
    spec:
      containers:
      - image: spring-petclinic-api-gateway:latest
        name: api-gateway
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 15
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 1Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        - name: JAVA_TOOL_OPTIONS
          value: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8081,suspend=n"
        ports:
        - containerPort: 8080
      restartPolicy: Always
